---
# model
model_type: 'vgg9'                   # "cnn", "resnet18", "vgg9"
cnn_hidden_size: [64, 128, 128]
# resnet_hidden_size: [64, 64, 128, 256, 512]

# data
dataset_type: 'CIFAR10'              # "MNIST", "CIFAR10" or "image100"
data_shape: [3, 32, 32]             # MNIST is [1, 28, 28], CIFAR10 is [3, 32, 32] and image100 is [3, 144, 144]
classes_size: 10                    # MNIST is 10, CIFAR10 is 10, image100 is 100
data_partition_pattern: 0           # 0, 1, or 2. (0 is iid while 1 and 2 are both non-iid)
non_iid_ratio: 7                    # make sure: 0 < non_iid_ratio < 10

# batch size
local_batch_size: 32                # local training batch size
test_batch_size: 32                 # test batch size of the server
client_test_batch_size: 32

# training setting
lr: 0.1
decay_rate: 0.993
min_lr: 0.001
momentum: -1                        # momentum < 0 means the momentum is None
weight_decay: 0

# global control
client_num: 10                       # total number of clients (not the number of selected clients)
epoch_num: 500
local_iters: 50                      # local training step of the client in each epoch

# CUDA
server_use_cuda: True
server_cuda: '3'                    # which gpu to choose for server
client_use_cuda: True
client_cuda: '-1'                   # '-1' means that client chooses the gpu adaptively according to the process id

# path
dataset_path: '/data/slwang/datasets/'

# seed
model_init_seed: 2020
client_selection_seed: 2020
data_partition_seed: 2020
